name: local_image_provider
description: A library for retrieving the metadata and contents of the images and albums on a mobile device.
version: 2.0.0
homepage: https://github.com/csdcorp/local_image_provider

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  json_serializable: ^3.2.5

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.local_image_provider
        pluginClass: LocalImageProviderPlugin
      ios:
        pluginClass: LocalImageProviderPlugin

